const CUSTOMER_KEY='velvet_vogue_customer';
const authView=document.getElementById('accountAuth'), profileView=document.getElementById('accountProfile'), message=document.getElementById('accountMessage');
function showProfile(customer){ authView.hidden=true; profileView.hidden=false; document.getElementById('profileName').textContent=customer.firstName||'Client'; document.getElementById('profileEmail').textContent=customer.email; }
const savedCustomer=JSON.parse(localStorage.getItem(CUSTOMER_KEY)||'null'); if(savedCustomer) showProfile(savedCustomer);
document.querySelectorAll('[data-account-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-account-tab]').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.account-form').forEach(x=>x.classList.remove('active'));document.getElementById(button.dataset.form).classList.add('active');message.textContent='';}));
document.getElementById('signInForm').addEventListener('submit',event=>{event.preventDefault();if(!event.currentTarget.checkValidity()){event.currentTarget.reportValidity();return;}const data=new FormData(event.currentTarget),known=JSON.parse(localStorage.getItem(CUSTOMER_KEY)||'null');const customer=known&&known.email===data.get('email')?known:{firstName:'Client',email:data.get('email')};localStorage.setItem(CUSTOMER_KEY,JSON.stringify(customer));showProfile(customer);});
document.getElementById('registerForm').addEventListener('submit',event=>{event.preventDefault();if(!event.currentTarget.checkValidity()){event.currentTarget.reportValidity();return;}const data=new FormData(event.currentTarget),customer={firstName:data.get('firstName'),lastName:data.get('lastName'),email:data.get('email')};localStorage.setItem(CUSTOMER_KEY,JSON.stringify(customer));showProfile(customer);});
document.getElementById('adminForm').addEventListener('submit',event=>{event.preventDefault();if(!event.currentTarget.checkValidity()){event.currentTarget.reportValidity();return;}const data=new FormData(event.currentTarget);if(veloLogin(data.get('username'),data.get('password')))window.location.href='admin.html';else{message.textContent='Incorrect administrator username or password.';event.currentTarget.querySelector('[name="password"]').value='';event.currentTarget.querySelector('[name="password"]').focus();}});
document.getElementById('forgotPassword').addEventListener('click',()=>message.textContent='Enter your email above. In a live store, a secure reset link would be sent to you.');
document.getElementById('signOutButton').addEventListener('click',()=>{localStorage.removeItem(CUSTOMER_KEY);profileView.hidden=true;authView.hidden=false;document.getElementById('signInForm').reset();});
